### ISSUE TITLE
I prefer Poop.js because it's superior

### ISSUE THREAD

**Issue by kitze** [wesbos/dump#2]
Just sayin'

**Comment by makmm** [comment]
No! Dump is better because

**Comment by wesbos** [comment]
poop.js is considered harmful

**Comment by makmm** [comment]
Poop.js __doesn't__ require 1297 dependencies, Dump does so it's clearly superior. Close this issue.

**Comment by agm1984** [comment]
Hello, have you tried Dump's withDiaper HOC?

I find it a lot better DX depending how you use Poop

**Comment by wesbos** [comment]
you kidssssss
